*** Variables ***

${PARAGRAPH_TEXT_FIELD}    name=paras
${ALL_MEAT_OPT}            xpath=//*[@id="any-ipsum-all-custom"]
${MEAT_AND_FILLER_OPT}     //*[@id="any-ipsum-custom-and-filler"]
${START_W_LOREM_CHECKBOX}  xpath=//*[@id="start-with-lorem"]
${SPICY_CHECKBOX}          id=spicy-jalapeno
${SUBMIT_BUTTON}           //*[@value="Give Me Bacon"]
${PARAGRAPH_CONTAINER}     xpath=//*[@id="container"]